name: snn-gpu-acceleration
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - brotli-python=1.0.9=py313h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - contourpy=1.3.1=py313h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - deprecated=1.2.13=py313hca03da5_0
  - expat=2.7.1=h313beb8_0
  - filelock=3.17.0=py313hca03da5_0
  - fonttools=4.55.3=py313h80987f9_0
  - freetype=2.13.3=h47d26ad_0
  - fsspec=2025.5.1=py313h7eb115d_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py313h5c1b81f_0
  - importlib-metadata=8.5.0=py313hca03da5_0
  - jinja2=3.1.6=py313hca03da5_0
  - jpeg=9e=h80987f9_3
  - kiwisolver=1.4.8=py313h313beb8_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libcxx=17.0.6=he5c5206_3
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libmpdec=4.0.0=h80987f9_0
  - libopenblas=0.3.29=hea593b9_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libtiff=4.7.0=h91aec0a_0
  - libtorch=2.5.1=gpu_mps_h7b1bc93_204
  - libuv=1.48.0=h80987f9_0
  - libwebp-base=1.3.2=h80987f9_1
  - llvm-openmp=17.0.6=h2f17746_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py313h80987f9_0
  - matplotlib=3.10.0=py313hca03da5_1
  - matplotlib-base=3.10.0=py313hb68df00_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py313hca03da5_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.4.2=py313hca03da5_0
  - nomkl=3.0=0
  - numpy=2.2.5=py313hdcf7240_0
  - numpy-base=2.2.5=py313h9d8309b_0
  - openjpeg=2.5.2=hba36e21_1
  - openssl=3.0.16=h02f6b3c_0
  - opentelemetry-api=1.30.0=py313hca03da5_0
  - packaging=24.2=py313hca03da5_0
  - pillow=11.1.0=py313h41ba818_1
  - pip=25.1=pyhc872135_2
  - pyparsing=3.2.0=py313hca03da5_0
  - python=3.13.5=h2eb94d5_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python_abi=3.13=0_cp313
  - pytorch=2.5.1=gpu_mps_py313hbd1d365_204
  - readline=8.2=h1a28f6b_0
  - scipy=1.15.3=py313hd7edaaf_0
  - setuptools=72.1.0=py313hca03da5_0
  - six=1.17.0=py313hca03da5_0
  - sleef=3.5.1=h80987f9_2
  - sqlite=3.45.3=h80987f9_0
  - sympy=1.13.3=py313hca03da5_1
  - tk=8.6.14=h6ba3021_1
  - tornado=6.5.1=py313h80987f9_0
  - typing_extensions=4.12.2=py313hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py313hca03da5_0
  - wrapt=1.17.0=py313h80987f9_0
  - xz=5.6.4=h80987f9_1
  - zipp=3.21.0=py313hca03da5_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/snn-gpu-acceleration
